name: sidecar_applications_workspace

environment:
  sdk: ^3.5.0-311.0.dev

dependencies:
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.11
  built_value_generator: ^8.9.2
  freezed: ^2.5.3
  json_serializable: ^6.8.0
  lints: ^4.0.0
  test: ^1.25.5

workspace:
  - nested_a
  - nested_b
